baseurl             = "https://www.asgeirberg.org"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa"
author              = "Ásgeir Berg Matthíasson"
title               = "Ásgeir Berg Matthíasson"
pygmentsuseclasses  = true
#disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-123-45"

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "About"
weight                 = -120
identifier             = "about"
url                    = "about/"

[[menu.main]]
name                   = "Research"
weight                 = -110
identifier             = "research"
url                    = "research/"
 
[[menu.main]]
name                   = "CV"
weight                 = -100
url                    = "cv/cv_english_full_asgeir_matthiasson.pdf"

[[menu.main]]
name                   = "fyrir öll x"
weight                 = -90
url                    = "fyrirollx"

[[menu.main]]
name                   = "Contact"
weight                 = -80
identifier             = "code"
url                    = "mailto:asgeirberg@hi.is"

[params]
#latestpostscount       = 1                            # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Ásgeir Berg Matthíasson"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Don't panic"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
highlightjs            = true
instagram              = "//instagram.com/asgeirberg"
lang                   = "en"
linkedin               = "//st-andrews.academia.edu/%C3%81sgeirBergMatth%C3%ADasson"
facebook 			   = "//facebook.com/asgeirberg"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = ""                            # appears in the site header when set to a non-empty string
twitter                = "//twitter.com/asgeirberg"
# highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
# highlightjsStyle     = "darcula"

piwik				   = false                         # If true, Piwik integration is enabled
# piwik_url            = "//www.example.com/piwik/"    # URL to your Piwik installation. Must End with a slash
# piwik_id			   = 2                             # Id of your site in Piwik

avatar                 = "img/profile.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# gravatar             = ""                # do not use in the same time as avatar

# The following are DEPRECATED.
gatracker              = "XYZ" # use googleAnalytics instead
initials               = "ad"  # displayed on single post page; deprecated in v0.3.0.
